parameters:
    assimtech_dislog.api_call.factory.class: Assimtech\Dislog\Factory\ApiCallFactory

    assimtech_dislog.generator.unique_id.class: Assimtech\Dislog\Identity\UniqueIdGenerator

    assimtech_dislog.serializer.string.class: Assimtech\Dislog\Serializer\StringSerializer

    assimtech_dislog.processor.regex_replace.class: Assimtech\Dislog\Processor\RegexReplace
    assimtech_dislog.processor.string_replace.class: Assimtech\Dislog\Processor\StringReplace


services:
    assimtech_dislog.api_call.factory:
        class: %assimtech_dislog.api_call.factory.class%

    assimtech_dislog.generator.unique_id:
        class: %assimtech_dislog.generator.unique_id.class%

    assimtech_dislog.serializer.string:
        class: %assimtech_dislog.serializer.string.class%
